# Generated by Django 2.2 on 2020-12-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='transaction_amount',
            field=models.IntegerField(blank=True, max_length=35),
        ),
    ]
