# Generated by Django 2.2 on 2020-12-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201212_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='transaction_amount',
            field=models.IntegerField(blank=True),
        ),
    ]
