# Generated by Django 2.2 on 2020-12-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201212_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
