# Generated by Django 2.2 on 2020-12-29 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201229_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trades',
            name='lot_size',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True, verbose_name='Lot size'),
        ),
    ]
