# Generated by Django 2.2 on 2020-12-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201212_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='transaction_complete',
            field=models.BooleanField(default=True),
        ),
    ]
