# Generated by Django 2.2 on 2020-12-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_transactions_transaction_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='acc_balance',
            field=models.IntegerField(default=1, verbose_name='Account balance on that transaction'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transaction_complete',
            field=models.BooleanField(default=False),
        ),
    ]
