# Generated by Django 2.2 on 2020-12-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201212_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='acc_balance',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='Account balance on that transaction'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transaction_complete',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
