# Generated by Django 2.2 on 2021-02-05 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201229_2359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactions',
            options={'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.CreateModel(
            name='Requsest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_type', models.CharField(default='withdrawl', max_length=50, verbose_name='Type')),
                ('requested_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=9999999)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Request Date')),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Requsest',
                'verbose_name_plural': 'Requsests',
            },
        ),
    ]
