# Generated by Django 2.2 on 2021-02-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210205_2134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requsest',
            options={},
        ),
        migrations.AddField(
            model_name='requsest',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
