# Generated by Django 2.2 on 2020-12-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20201212_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='acc_balance',
            field=models.IntegerField(blank=True, null=True, verbose_name='Account balance after that transaction'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transaction_complete',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
