# Generated by Django 2.2 on 2020-12-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20201212_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='transaction_complete',
            field=models.BooleanField(default=False),
        ),
    ]
