# Generated by Django 2.2 on 2020-12-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20201212_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
