# Generated by Django 2.2 on 2020-12-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20201214_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='main_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='plan',
            field=models.CharField(choices=[('Not subscribed', 'Not subscribed'), ('Basic', 'basic'), ('standard', 'standard'), ('gold', 'gold'), ('diamond', 'diamond')], default='Not subscribed', max_length=10),
        ),
    ]
