# Generated by Django 2.2 on 2020-12-15 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20201215_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='plan',
            field=models.CharField(choices=[('Not subscribed', 'Not subscribed'), ('Basic', 'basic'), ('standard', 'standard'), ('gold', 'gold'), ('diamond', 'diamond')], default='Not subscribed', max_length=20),
        ),
    ]
